version: "3.8"
services:
  api:
    build: ./mock-api
    container_name: react_todo_mock_api_c
    ports:
      - '3001:3001'
  ui:
    build: ./
    container_name: react_todo_c
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true